definitions:
  License:
    properties:
      href:
        description: URL of the license
        format: uri
        maxLength: 65536
        minLength: 1
        title: Href
        type: string
      name:
        description: Name of the license
        title: Name
        type: string
    required:
      - name
    title: License
    type: object
  Link:
    properties:
      href:
        description: URL of the link
        format: uri
        maxLength: 65536
        minLength: 1
        title: Href
        type: string
      label:
        description: Label of the link
        title: Label
        type: string
    required:
      - label
      - href
    title: Link
    type: object
  Maintainer:
    properties:
      github_username:
        description: GitHub username of the maintainer
        title: Github Username
        type: string
      name:
        description: Name of the maintainer
        title: Name
        type: string
    required:
      - name
    title: Maintainer
    type: object
  Store:
    properties:
      name:
        description: Name of the store
        title: Name
        type: string
      url:
        description: URL of the store
        format: uri
        maxLength: 65536
        minLength: 1
        title: Url
        type: string
    required:
      - name
      - url
    title: Store
    type: object
properties:
  demo:
    default: false
    description: Whether the dataset is a demo dataset
    title: Demo
    type: boolean
  description:
    description: Description of the dataset
    title: Description
    type: string
  doi_citation:
    format: uri
    maxLength: 2083
    minLength: 1
    title: Doi Citation
    type: string
  license:
    $ref: "#/definitions/License"
  links:
    items:
      $ref: "#/definitions/Link"
    title: Links
    type: array
  maintainers:
    items:
      $ref: "#/definitions/Maintainer"
    title: Maintainers
    type: array
  name:
    description: Name of the dataset
    title: Name
    type: string
  stores:
    items:
      $ref: "#/definitions/Store"
    title: Stores
    type: array
  tags:
    description: Tags of the dataset
    items:
      type: string
    title: Tags
    type: array
  thumbnail:
    description: Thumbnail of the dataset
    format: uri
    maxLength: 2083
    minLength: 1
    title: Thumbnail
    type: string
required:
  - name
  - description
  - stores
  - maintainers
title: Dataset
type: object
