title: "LEAP Data Library"
description: >
  A collection of Pangeo Forge Recipes to ingest datasets into the LEAP Data Library.
recipes:
  - id: "METAFLUX_GPP_RECO_monthly"
    object: "metaflux:METAFLUX_GPP_RECO_monthly"
    description: Monthly METAFLUX_GPP_RECO data
    provenance:
      providers:
        - name: "Zenodo"
          description: "Zenodo"
          roles:
            - host
          url: https://zenodo.org/record/7761881#.ZFv9OS-B30p
        - name: "Nathaniel et al."
          description: "Authors of MetaFlux: Meta-learning global carbon fluxes from sparse spatiotemporal observations"
          roles:
            - producer
            - licensor
      license: "CC-BY-4.0"
  - id: "METAFLUX_GPP_RECO_daily"
    object: "metaflux:METAFLUX_GPP_RECO_daily"
    description: Daily METAFLUX_GPP_RECO data
    provenance:
      providers:
        - name: "Zenodo"
          description: "Zenodo"
          roles:
            - host
          url: https://zenodo.org/record/7761881#.ZFv9OS-B30p
        - name: "Nathaniel et al."
          description: "Authors of MetaFlux: Meta-learning global carbon fluxes from sparse spatiotemporal observations"
          roles:
            - producer
            - licensor
      license: "CC-BY-4.0"
  - id: CASM
    object: "casm:CASM"
    description: A long-term Consistent Artificial-intelligence based Soil Moisture dataset based on machine learning and remote sensing
    provenance:
      providers:
        - name: "Zenodo"
          description: "Zenodo"
          roles:
            - host
          url: https://zenodo.org/record/7072512#.ZFj3h-zMK3J
        - name: "Skulovich and Gentine"
          description: "Authors of CASM: A long-term Consistent Artificial-intelligence based Soil Moisture dataset based on machine learning and remote sensing"
          roles:
            - producer
            - licensor
      license: "CC-BY-4.0"
  - id: climsim-highres-mli
    object: "climsim:climsim_highres_mli"
    description: "Input ('mli') product of ClimSim high resolution real geography dataset."
    provenance:
      providers:
        - name: "Hugging Face"
          description: "Hugging Face"
          roles:
            - host
          url: https://huggingface.co/datasets/LEAP/ClimSim_high-res
        - name: "Sungduk Yu et al"
          description: "ClimSim: An open large-scale dataset for training high-resolution physics emulators in hybrid multi-scale climate simulators"
          roles:
            - producer
            - licensor
          url: https://arxiv.org/abs/2306.08754
      license: "Apache-2.0"
  - id: climsim-highres-mlo
    object: "climsim:climsim_highres_mlo"
    description: "Output ('mlo') product of ClimSim high resolution real geography dataset."
    provenance:
      providers:
        - name: "Hugging Face"
          description: "Hugging Face"
          roles:
            - host
          url: https://huggingface.co/datasets/LEAP/ClimSim_high-res
        - name: "Sungduk Yu et al"
          description: "ClimSim: An open large-scale dataset for training high-resolution physics emulators in hybrid multi-scale climate simulators"
          roles:
            - producer
            - licensor
          url: https://arxiv.org/abs/2306.08754
    license: "Apache-2.0"
maintainers:
  - name: "Julius Busecke"
    orcid: 0000-0001-8571-865X
    github: jbusecke
  - name: "Charles Stern"
    orcid: 0000-0002-4078-0852
    github: cisaacstern
