name: GCS Bucket Size report

on:
  workflow_dispatch:
    inputs:
      bucket:
        description: "input bucket url. ex: gs://leap-scratch"
        required: true
        type: string
      min_size_gb:
        description: "Minimum size in GB to report"
        required: false
        default: "10"
        type: string

  schedule:
    - cron: "0 0 * * 0"

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v6

      - name: install cloud-dir-size
        run: |
          uv add "git+https://${{ secrets.GH_PAT }}@github.com/norlandrhagen/cloud-dir-size.git"

      - name: run
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            cloud-dir-size \
              --bucket-url "${{ inputs.bucket }}" \
              --min-size-gb "${{ inputs.min_size_gb }}" \
              --send-slack \
              --slack-webhook-url "${{ secrets.SLACK_WEBHOOK }}"
          else

            buckets=(
              "gs://leap-scratch"
              "gs://leap-persistent"
              "gs://leap-persistent-ro"
            )

            for bucket in "${buckets[@]}"; do
              echo "Getting size of dirs in: $bucket"
              cloud-dir-size \
                --bucket-url "$bucket" \
                --min-size-gb 10 \
                --send-slack \
                --slack-webhook-url "${{ secrets.SLACK_WEBHOOK }}"
            done
          fi
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
